/*candidates */
INSERT INTO departments (name)
VALUES
('Customer Service'),
('Deli'),
('Bakery'),
('Produce'),
('Meat'),
('Grocery');

/*roles*/
INSERT INTO roles (title, salary, department_id)
VALUES
('Bagger', 14.00, 1),
('Cashier', 16.00, 1),
('CSS', 18.00, 1),
('Deli Clerk', 16.00, 2),
('Meat Specialist', 18.00, 2),
('Bakery Clerk', 14.00, 3),
('Baker', 18.00, 3),
('Cake Decorator', 18.00, 3),
('Fruit Cutter', 15.00, 4),
('Produce Clerk', 14.00, 4),
('Meat Clerk', 16.00, 5),
('Meat Cutter', 18.00, 5),
('Seafood Specialist', 18.00, 5),
('Grocery Clerk', 14.00, 6),
('GRS', 18.00, 6);

/*voters*/
INSERT INTO employee (first_name, last_name, role_id, manager_id)
VALUES
  ('James', 'Fraser', 1, 1),
  ('Jack', 'London', 1, 1),
  ('Robert', 'Bruce', 1, 1),
  ('Peter', 'Greenaway', 1, 1),
  ('Derek', 'Jarman', 1, 1),
  ('Paolo', 'Pasolini', 1, 1),
  ('Heathcote', 'Williams', 1, 1),
  ('Sandy', 'Powell', 2, 1),
  ('Emil', 'Zola', 2, 1),
  ('Sissy', 'Coalpits', 2, 1),
  ('Antoinette', 'Capet', 2, 1),
  ('Samuel', 'Delany', 2, 1),
  ('Tony', 'Duvert', 3, 1),
  ('Dennis', 'Cooper', 3, 1),
  ('Monica', 'Bellucci', 3, 1),
  ('Samuel', 'Johnson', 4, 2),
  ('John', 'Dryden', 4, 2),
  ('Alexander', 'Pope', 5, 2),
  ('Lionel', 'Johnson', 5, 2),
  ('Aubrey', 'Beardsley', 6, 3),
  ('Tulse', 'Luper', 6, 3),
  ('William', 'Morris', 6, 3),
  ('George', 'Shaw', 7, 3),
  ('Arnold', 'Bennett', 8, 3),
  ('Algernon', 'Blackwood', 9, 4),
  ('Rhoda', 'Broughton', 10, 4),
  ('Hart', 'Crane', 10, 4),
  ('Vitorio', 'DeSica', 10, 4),
  ('Wilkie', 'Collins', 11, 5),
  ('Elizabeth', 'Gaskell', 11, 5),
  ('George', 'Sand', 11, 5),
  ('Vernon', 'Lee', 12, 5),
  ('Arthur', 'Machen', 12, 5),
  ('Frederick', 'Marryat', 12, 5),
  ('Harriet', 'Martineau', 13, 5),
  ('George', 'Meredith', 14, 6),
  ('Margaret', 'Oliphant', 14, 6),
  ('Anthony', 'Trollope', 14, 6),
  ('Charlotte', 'Yonge', 14, 6),
  ('Horace', 'Walpole', 14, 6),
  ('Matthew', 'Lewis', 14, 6),
  ('William', 'Bedford', 14, 6),
  ('Anne', 'Radcliffe', 14, 6),
  ('Charles', 'Brown', 14, 6),
  ('Eliza', 'Parsons', 14, 6),
  ('Susan', 'Hill', 14, 6),
  ('Sydney', 'Owenson', 14, 6),
  ('Hubert', 'Crackanthorpe', 14, 6),
  ('William', 'Carleton', 15, 6),
  ('Gerald', 'Griffin', 15, 6);